version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sales-course
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      - postgres-compose-network  

networks: 
  postgres-compose-network:
    driver: bridge